services:
  - type: web
    name: the-convergence
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: STAGE
        value: Production
      - key: DATABASE_URL
        value: postgresql://postgres.efeisqqzrcvqnztsiiin:atichatdecho@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: JWT_USER_SECRET
        generateValue: true
      - key: SERVER_BODY_LIMIT
        value: "2097152"
      - key: SERVER_TIMEOUT
        value: "30"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dtqrphm2b"
      - key: CLOUDINARY_API_KEY
        value: "332441267638168"
      - key: CLOUDINARY_API_SECRET
        value: "esTSyyi2tudHGwUnnX-zxdnOAxU"
      - key: JWT_USER_REFRESH_SECRET
        value: "default_secret_key_for_development"
      - key: MAX_CREW_PER_MISSION
        value: "5"
      - key: JWT_LIFE_TIME_DAYS
        value: "7"
